/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as AppWizardRouteImport } from './routes/app.wizard'
import { Route as AppVnptRouteImport } from './routes/app.vnpt'
import { Route as AppUploadRouteImport } from './routes/app.upload'
import { Route as AppSmartuxRouteImport } from './routes/app.smartux'
import { Route as AppSettingsRouteImport } from './routes/app.settings'
import { Route as AppResolutionRouteImport } from './routes/app.resolution'
import { Route as AppQueueRouteImport } from './routes/app.queue'
import { Route as AppNotificationsRouteImport } from './routes/app.notifications'
import { Route as AppExportRouteImport } from './routes/app.export'
import { Route as AppEvidenceSearchRouteImport } from './routes/app.evidence-search'
import { Route as AppEvidenceRouteImport } from './routes/app.evidence'
import { Route as AppEventRegistryRouteImport } from './routes/app.event-registry'
import { Route as AppEventLibraryRouteImport } from './routes/app.event-library'
import { Route as AppEkycRouteImport } from './routes/app.ekyc'
import { Route as AppDraftsRouteImport } from './routes/app.drafts'
import { Route as AppCollectiveRouteImport } from './routes/app.collective'
import { Route as AppChatbotRouteImport } from './routes/app.chatbot'
import { Route as AppCascadeRouteImport } from './routes/app.cascade'
import { Route as AppAuditRouteImport } from './routes/app.audit'
import { Route as AppAssignmentRouteImport } from './routes/app.assignment'
import { Route as AppAnalyticsRouteImport } from './routes/app.analytics'
import { Route as AppAiPrecheckRouteImport } from './routes/app.ai-precheck'
import { Route as AppReviewIdRouteImport } from './routes/app.review.$id'
import { Route as AppResolutionIdRouteImport } from './routes/app.resolution.$id'
import { Route as AppManagerResultsRouteImport } from './routes/app.manager.results'
import { Route as AppManagerResultRouteImport } from './routes/app.manager.result'
import { Route as AppManagerCollectiveRouteImport } from './routes/app.manager.collective'
import { Route as AppCommitteeInboxRouteImport } from './routes/app.committee.inbox'
import { Route as AppCollectiveIdRouteImport } from './routes/app.collective.$id'
import { Route as AppManagerResultsApplicationIdRouteImport } from './routes/app.manager.results.$applicationId'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppWizardRoute = AppWizardRouteImport.update({
  id: '/wizard',
  path: '/wizard',
  getParentRoute: () => AppRoute,
} as any)
const AppVnptRoute = AppVnptRouteImport.update({
  id: '/vnpt',
  path: '/vnpt',
  getParentRoute: () => AppRoute,
} as any)
const AppUploadRoute = AppUploadRouteImport.update({
  id: '/upload',
  path: '/upload',
  getParentRoute: () => AppRoute,
} as any)
const AppSmartuxRoute = AppSmartuxRouteImport.update({
  id: '/smartux',
  path: '/smartux',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppResolutionRoute = AppResolutionRouteImport.update({
  id: '/resolution',
  path: '/resolution',
  getParentRoute: () => AppRoute,
} as any)
const AppQueueRoute = AppQueueRouteImport.update({
  id: '/queue',
  path: '/queue',
  getParentRoute: () => AppRoute,
} as any)
const AppNotificationsRoute = AppNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => AppRoute,
} as any)
const AppExportRoute = AppExportRouteImport.update({
  id: '/export',
  path: '/export',
  getParentRoute: () => AppRoute,
} as any)
const AppEvidenceSearchRoute = AppEvidenceSearchRouteImport.update({
  id: '/evidence-search',
  path: '/evidence-search',
  getParentRoute: () => AppRoute,
} as any)
const AppEvidenceRoute = AppEvidenceRouteImport.update({
  id: '/evidence',
  path: '/evidence',
  getParentRoute: () => AppRoute,
} as any)
const AppEventRegistryRoute = AppEventRegistryRouteImport.update({
  id: '/event-registry',
  path: '/event-registry',
  getParentRoute: () => AppRoute,
} as any)
const AppEventLibraryRoute = AppEventLibraryRouteImport.update({
  id: '/event-library',
  path: '/event-library',
  getParentRoute: () => AppRoute,
} as any)
const AppEkycRoute = AppEkycRouteImport.update({
  id: '/ekyc',
  path: '/ekyc',
  getParentRoute: () => AppRoute,
} as any)
const AppDraftsRoute = AppDraftsRouteImport.update({
  id: '/drafts',
  path: '/drafts',
  getParentRoute: () => AppRoute,
} as any)
const AppCollectiveRoute = AppCollectiveRouteImport.update({
  id: '/collective',
  path: '/collective',
  getParentRoute: () => AppRoute,
} as any)
const AppChatbotRoute = AppChatbotRouteImport.update({
  id: '/chatbot',
  path: '/chatbot',
  getParentRoute: () => AppRoute,
} as any)
const AppCascadeRoute = AppCascadeRouteImport.update({
  id: '/cascade',
  path: '/cascade',
  getParentRoute: () => AppRoute,
} as any)
const AppAuditRoute = AppAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => AppRoute,
} as any)
const AppAssignmentRoute = AppAssignmentRouteImport.update({
  id: '/assignment',
  path: '/assignment',
  getParentRoute: () => AppRoute,
} as any)
const AppAnalyticsRoute = AppAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AppRoute,
} as any)
const AppAiPrecheckRoute = AppAiPrecheckRouteImport.update({
  id: '/ai-precheck',
  path: '/ai-precheck',
  getParentRoute: () => AppRoute,
} as any)
const AppReviewIdRoute = AppReviewIdRouteImport.update({
  id: '/review/$id',
  path: '/review/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppResolutionIdRoute = AppResolutionIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AppResolutionRoute,
} as any)
const AppManagerResultsRoute = AppManagerResultsRouteImport.update({
  id: '/manager/results',
  path: '/manager/results',
  getParentRoute: () => AppRoute,
} as any)
const AppManagerResultRoute = AppManagerResultRouteImport.update({
  id: '/manager/result',
  path: '/manager/result',
  getParentRoute: () => AppRoute,
} as any)
const AppManagerCollectiveRoute = AppManagerCollectiveRouteImport.update({
  id: '/manager/collective',
  path: '/manager/collective',
  getParentRoute: () => AppRoute,
} as any)
const AppCommitteeInboxRoute = AppCommitteeInboxRouteImport.update({
  id: '/committee/inbox',
  path: '/committee/inbox',
  getParentRoute: () => AppRoute,
} as any)
const AppCollectiveIdRoute = AppCollectiveIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AppCollectiveRoute,
} as any)
const AppManagerResultsApplicationIdRoute =
  AppManagerResultsApplicationIdRouteImport.update({
    id: '/$applicationId',
    path: '/$applicationId',
    getParentRoute: () => AppManagerResultsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/app/ai-precheck': typeof AppAiPrecheckRoute
  '/app/analytics': typeof AppAnalyticsRoute
  '/app/assignment': typeof AppAssignmentRoute
  '/app/audit': typeof AppAuditRoute
  '/app/cascade': typeof AppCascadeRoute
  '/app/chatbot': typeof AppChatbotRoute
  '/app/collective': typeof AppCollectiveRouteWithChildren
  '/app/drafts': typeof AppDraftsRoute
  '/app/ekyc': typeof AppEkycRoute
  '/app/event-library': typeof AppEventLibraryRoute
  '/app/event-registry': typeof AppEventRegistryRoute
  '/app/evidence': typeof AppEvidenceRoute
  '/app/evidence-search': typeof AppEvidenceSearchRoute
  '/app/export': typeof AppExportRoute
  '/app/notifications': typeof AppNotificationsRoute
  '/app/queue': typeof AppQueueRoute
  '/app/resolution': typeof AppResolutionRouteWithChildren
  '/app/settings': typeof AppSettingsRoute
  '/app/smartux': typeof AppSmartuxRoute
  '/app/upload': typeof AppUploadRoute
  '/app/vnpt': typeof AppVnptRoute
  '/app/wizard': typeof AppWizardRoute
  '/app/': typeof AppIndexRoute
  '/app/collective/$id': typeof AppCollectiveIdRoute
  '/app/committee/inbox': typeof AppCommitteeInboxRoute
  '/app/manager/collective': typeof AppManagerCollectiveRoute
  '/app/manager/result': typeof AppManagerResultRoute
  '/app/manager/results': typeof AppManagerResultsRouteWithChildren
  '/app/resolution/$id': typeof AppResolutionIdRoute
  '/app/review/$id': typeof AppReviewIdRoute
  '/app/manager/results/$applicationId': typeof AppManagerResultsApplicationIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/app/ai-precheck': typeof AppAiPrecheckRoute
  '/app/analytics': typeof AppAnalyticsRoute
  '/app/assignment': typeof AppAssignmentRoute
  '/app/audit': typeof AppAuditRoute
  '/app/cascade': typeof AppCascadeRoute
  '/app/chatbot': typeof AppChatbotRoute
  '/app/collective': typeof AppCollectiveRouteWithChildren
  '/app/drafts': typeof AppDraftsRoute
  '/app/ekyc': typeof AppEkycRoute
  '/app/event-library': typeof AppEventLibraryRoute
  '/app/event-registry': typeof AppEventRegistryRoute
  '/app/evidence': typeof AppEvidenceRoute
  '/app/evidence-search': typeof AppEvidenceSearchRoute
  '/app/export': typeof AppExportRoute
  '/app/notifications': typeof AppNotificationsRoute
  '/app/queue': typeof AppQueueRoute
  '/app/resolution': typeof AppResolutionRouteWithChildren
  '/app/settings': typeof AppSettingsRoute
  '/app/smartux': typeof AppSmartuxRoute
  '/app/upload': typeof AppUploadRoute
  '/app/vnpt': typeof AppVnptRoute
  '/app/wizard': typeof AppWizardRoute
  '/app': typeof AppIndexRoute
  '/app/collective/$id': typeof AppCollectiveIdRoute
  '/app/committee/inbox': typeof AppCommitteeInboxRoute
  '/app/manager/collective': typeof AppManagerCollectiveRoute
  '/app/manager/result': typeof AppManagerResultRoute
  '/app/manager/results': typeof AppManagerResultsRouteWithChildren
  '/app/resolution/$id': typeof AppResolutionIdRoute
  '/app/review/$id': typeof AppReviewIdRoute
  '/app/manager/results/$applicationId': typeof AppManagerResultsApplicationIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/app/ai-precheck': typeof AppAiPrecheckRoute
  '/app/analytics': typeof AppAnalyticsRoute
  '/app/assignment': typeof AppAssignmentRoute
  '/app/audit': typeof AppAuditRoute
  '/app/cascade': typeof AppCascadeRoute
  '/app/chatbot': typeof AppChatbotRoute
  '/app/collective': typeof AppCollectiveRouteWithChildren
  '/app/drafts': typeof AppDraftsRoute
  '/app/ekyc': typeof AppEkycRoute
  '/app/event-library': typeof AppEventLibraryRoute
  '/app/event-registry': typeof AppEventRegistryRoute
  '/app/evidence': typeof AppEvidenceRoute
  '/app/evidence-search': typeof AppEvidenceSearchRoute
  '/app/export': typeof AppExportRoute
  '/app/notifications': typeof AppNotificationsRoute
  '/app/queue': typeof AppQueueRoute
  '/app/resolution': typeof AppResolutionRouteWithChildren
  '/app/settings': typeof AppSettingsRoute
  '/app/smartux': typeof AppSmartuxRoute
  '/app/upload': typeof AppUploadRoute
  '/app/vnpt': typeof AppVnptRoute
  '/app/wizard': typeof AppWizardRoute
  '/app/': typeof AppIndexRoute
  '/app/collective/$id': typeof AppCollectiveIdRoute
  '/app/committee/inbox': typeof AppCommitteeInboxRoute
  '/app/manager/collective': typeof AppManagerCollectiveRoute
  '/app/manager/result': typeof AppManagerResultRoute
  '/app/manager/results': typeof AppManagerResultsRouteWithChildren
  '/app/resolution/$id': typeof AppResolutionIdRoute
  '/app/review/$id': typeof AppReviewIdRoute
  '/app/manager/results/$applicationId': typeof AppManagerResultsApplicationIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/login'
    | '/signup'
    | '/app/ai-precheck'
    | '/app/analytics'
    | '/app/assignment'
    | '/app/audit'
    | '/app/cascade'
    | '/app/chatbot'
    | '/app/collective'
    | '/app/drafts'
    | '/app/ekyc'
    | '/app/event-library'
    | '/app/event-registry'
    | '/app/evidence'
    | '/app/evidence-search'
    | '/app/export'
    | '/app/notifications'
    | '/app/queue'
    | '/app/resolution'
    | '/app/settings'
    | '/app/smartux'
    | '/app/upload'
    | '/app/vnpt'
    | '/app/wizard'
    | '/app/'
    | '/app/collective/$id'
    | '/app/committee/inbox'
    | '/app/manager/collective'
    | '/app/manager/result'
    | '/app/manager/results'
    | '/app/resolution/$id'
    | '/app/review/$id'
    | '/app/manager/results/$applicationId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/signup'
    | '/app/ai-precheck'
    | '/app/analytics'
    | '/app/assignment'
    | '/app/audit'
    | '/app/cascade'
    | '/app/chatbot'
    | '/app/collective'
    | '/app/drafts'
    | '/app/ekyc'
    | '/app/event-library'
    | '/app/event-registry'
    | '/app/evidence'
    | '/app/evidence-search'
    | '/app/export'
    | '/app/notifications'
    | '/app/queue'
    | '/app/resolution'
    | '/app/settings'
    | '/app/smartux'
    | '/app/upload'
    | '/app/vnpt'
    | '/app/wizard'
    | '/app'
    | '/app/collective/$id'
    | '/app/committee/inbox'
    | '/app/manager/collective'
    | '/app/manager/result'
    | '/app/manager/results'
    | '/app/resolution/$id'
    | '/app/review/$id'
    | '/app/manager/results/$applicationId'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/login'
    | '/signup'
    | '/app/ai-precheck'
    | '/app/analytics'
    | '/app/assignment'
    | '/app/audit'
    | '/app/cascade'
    | '/app/chatbot'
    | '/app/collective'
    | '/app/drafts'
    | '/app/ekyc'
    | '/app/event-library'
    | '/app/event-registry'
    | '/app/evidence'
    | '/app/evidence-search'
    | '/app/export'
    | '/app/notifications'
    | '/app/queue'
    | '/app/resolution'
    | '/app/settings'
    | '/app/smartux'
    | '/app/upload'
    | '/app/vnpt'
    | '/app/wizard'
    | '/app/'
    | '/app/collective/$id'
    | '/app/committee/inbox'
    | '/app/manager/collective'
    | '/app/manager/result'
    | '/app/manager/results'
    | '/app/resolution/$id'
    | '/app/review/$id'
    | '/app/manager/results/$applicationId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
  SignupRoute: typeof SignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/wizard': {
      id: '/app/wizard'
      path: '/wizard'
      fullPath: '/app/wizard'
      preLoaderRoute: typeof AppWizardRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/vnpt': {
      id: '/app/vnpt'
      path: '/vnpt'
      fullPath: '/app/vnpt'
      preLoaderRoute: typeof AppVnptRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/upload': {
      id: '/app/upload'
      path: '/upload'
      fullPath: '/app/upload'
      preLoaderRoute: typeof AppUploadRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/smartux': {
      id: '/app/smartux'
      path: '/smartux'
      fullPath: '/app/smartux'
      preLoaderRoute: typeof AppSmartuxRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/settings': {
      id: '/app/settings'
      path: '/settings'
      fullPath: '/app/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/resolution': {
      id: '/app/resolution'
      path: '/resolution'
      fullPath: '/app/resolution'
      preLoaderRoute: typeof AppResolutionRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/queue': {
      id: '/app/queue'
      path: '/queue'
      fullPath: '/app/queue'
      preLoaderRoute: typeof AppQueueRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/notifications': {
      id: '/app/notifications'
      path: '/notifications'
      fullPath: '/app/notifications'
      preLoaderRoute: typeof AppNotificationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/export': {
      id: '/app/export'
      path: '/export'
      fullPath: '/app/export'
      preLoaderRoute: typeof AppExportRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/evidence-search': {
      id: '/app/evidence-search'
      path: '/evidence-search'
      fullPath: '/app/evidence-search'
      preLoaderRoute: typeof AppEvidenceSearchRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/evidence': {
      id: '/app/evidence'
      path: '/evidence'
      fullPath: '/app/evidence'
      preLoaderRoute: typeof AppEvidenceRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/event-registry': {
      id: '/app/event-registry'
      path: '/event-registry'
      fullPath: '/app/event-registry'
      preLoaderRoute: typeof AppEventRegistryRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/event-library': {
      id: '/app/event-library'
      path: '/event-library'
      fullPath: '/app/event-library'
      preLoaderRoute: typeof AppEventLibraryRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/ekyc': {
      id: '/app/ekyc'
      path: '/ekyc'
      fullPath: '/app/ekyc'
      preLoaderRoute: typeof AppEkycRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/drafts': {
      id: '/app/drafts'
      path: '/drafts'
      fullPath: '/app/drafts'
      preLoaderRoute: typeof AppDraftsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/collective': {
      id: '/app/collective'
      path: '/collective'
      fullPath: '/app/collective'
      preLoaderRoute: typeof AppCollectiveRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/chatbot': {
      id: '/app/chatbot'
      path: '/chatbot'
      fullPath: '/app/chatbot'
      preLoaderRoute: typeof AppChatbotRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/cascade': {
      id: '/app/cascade'
      path: '/cascade'
      fullPath: '/app/cascade'
      preLoaderRoute: typeof AppCascadeRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/audit': {
      id: '/app/audit'
      path: '/audit'
      fullPath: '/app/audit'
      preLoaderRoute: typeof AppAuditRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/assignment': {
      id: '/app/assignment'
      path: '/assignment'
      fullPath: '/app/assignment'
      preLoaderRoute: typeof AppAssignmentRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/analytics': {
      id: '/app/analytics'
      path: '/analytics'
      fullPath: '/app/analytics'
      preLoaderRoute: typeof AppAnalyticsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/ai-precheck': {
      id: '/app/ai-precheck'
      path: '/ai-precheck'
      fullPath: '/app/ai-precheck'
      preLoaderRoute: typeof AppAiPrecheckRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/review/$id': {
      id: '/app/review/$id'
      path: '/review/$id'
      fullPath: '/app/review/$id'
      preLoaderRoute: typeof AppReviewIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/resolution/$id': {
      id: '/app/resolution/$id'
      path: '/$id'
      fullPath: '/app/resolution/$id'
      preLoaderRoute: typeof AppResolutionIdRouteImport
      parentRoute: typeof AppResolutionRoute
    }
    '/app/manager/results': {
      id: '/app/manager/results'
      path: '/manager/results'
      fullPath: '/app/manager/results'
      preLoaderRoute: typeof AppManagerResultsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/manager/result': {
      id: '/app/manager/result'
      path: '/manager/result'
      fullPath: '/app/manager/result'
      preLoaderRoute: typeof AppManagerResultRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/manager/collective': {
      id: '/app/manager/collective'
      path: '/manager/collective'
      fullPath: '/app/manager/collective'
      preLoaderRoute: typeof AppManagerCollectiveRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/committee/inbox': {
      id: '/app/committee/inbox'
      path: '/committee/inbox'
      fullPath: '/app/committee/inbox'
      preLoaderRoute: typeof AppCommitteeInboxRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/collective/$id': {
      id: '/app/collective/$id'
      path: '/$id'
      fullPath: '/app/collective/$id'
      preLoaderRoute: typeof AppCollectiveIdRouteImport
      parentRoute: typeof AppCollectiveRoute
    }
    '/app/manager/results/$applicationId': {
      id: '/app/manager/results/$applicationId'
      path: '/$applicationId'
      fullPath: '/app/manager/results/$applicationId'
      preLoaderRoute: typeof AppManagerResultsApplicationIdRouteImport
      parentRoute: typeof AppManagerResultsRoute
    }
  }
}

interface AppCollectiveRouteChildren {
  AppCollectiveIdRoute: typeof AppCollectiveIdRoute
}

const AppCollectiveRouteChildren: AppCollectiveRouteChildren = {
  AppCollectiveIdRoute: AppCollectiveIdRoute,
}

const AppCollectiveRouteWithChildren = AppCollectiveRoute._addFileChildren(
  AppCollectiveRouteChildren,
)

interface AppResolutionRouteChildren {
  AppResolutionIdRoute: typeof AppResolutionIdRoute
}

const AppResolutionRouteChildren: AppResolutionRouteChildren = {
  AppResolutionIdRoute: AppResolutionIdRoute,
}

const AppResolutionRouteWithChildren = AppResolutionRoute._addFileChildren(
  AppResolutionRouteChildren,
)

interface AppManagerResultsRouteChildren {
  AppManagerResultsApplicationIdRoute: typeof AppManagerResultsApplicationIdRoute
}

const AppManagerResultsRouteChildren: AppManagerResultsRouteChildren = {
  AppManagerResultsApplicationIdRoute: AppManagerResultsApplicationIdRoute,
}

const AppManagerResultsRouteWithChildren =
  AppManagerResultsRoute._addFileChildren(AppManagerResultsRouteChildren)

interface AppRouteChildren {
  AppAiPrecheckRoute: typeof AppAiPrecheckRoute
  AppAnalyticsRoute: typeof AppAnalyticsRoute
  AppAssignmentRoute: typeof AppAssignmentRoute
  AppAuditRoute: typeof AppAuditRoute
  AppCascadeRoute: typeof AppCascadeRoute
  AppChatbotRoute: typeof AppChatbotRoute
  AppCollectiveRoute: typeof AppCollectiveRouteWithChildren
  AppDraftsRoute: typeof AppDraftsRoute
  AppEkycRoute: typeof AppEkycRoute
  AppEventLibraryRoute: typeof AppEventLibraryRoute
  AppEventRegistryRoute: typeof AppEventRegistryRoute
  AppEvidenceRoute: typeof AppEvidenceRoute
  AppEvidenceSearchRoute: typeof AppEvidenceSearchRoute
  AppExportRoute: typeof AppExportRoute
  AppNotificationsRoute: typeof AppNotificationsRoute
  AppQueueRoute: typeof AppQueueRoute
  AppResolutionRoute: typeof AppResolutionRouteWithChildren
  AppSettingsRoute: typeof AppSettingsRoute
  AppSmartuxRoute: typeof AppSmartuxRoute
  AppUploadRoute: typeof AppUploadRoute
  AppVnptRoute: typeof AppVnptRoute
  AppWizardRoute: typeof AppWizardRoute
  AppIndexRoute: typeof AppIndexRoute
  AppCommitteeInboxRoute: typeof AppCommitteeInboxRoute
  AppManagerCollectiveRoute: typeof AppManagerCollectiveRoute
  AppManagerResultRoute: typeof AppManagerResultRoute
  AppManagerResultsRoute: typeof AppManagerResultsRouteWithChildren
  AppReviewIdRoute: typeof AppReviewIdRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAiPrecheckRoute: AppAiPrecheckRoute,
  AppAnalyticsRoute: AppAnalyticsRoute,
  AppAssignmentRoute: AppAssignmentRoute,
  AppAuditRoute: AppAuditRoute,
  AppCascadeRoute: AppCascadeRoute,
  AppChatbotRoute: AppChatbotRoute,
  AppCollectiveRoute: AppCollectiveRouteWithChildren,
  AppDraftsRoute: AppDraftsRoute,
  AppEkycRoute: AppEkycRoute,
  AppEventLibraryRoute: AppEventLibraryRoute,
  AppEventRegistryRoute: AppEventRegistryRoute,
  AppEvidenceRoute: AppEvidenceRoute,
  AppEvidenceSearchRoute: AppEvidenceSearchRoute,
  AppExportRoute: AppExportRoute,
  AppNotificationsRoute: AppNotificationsRoute,
  AppQueueRoute: AppQueueRoute,
  AppResolutionRoute: AppResolutionRouteWithChildren,
  AppSettingsRoute: AppSettingsRoute,
  AppSmartuxRoute: AppSmartuxRoute,
  AppUploadRoute: AppUploadRoute,
  AppVnptRoute: AppVnptRoute,
  AppWizardRoute: AppWizardRoute,
  AppIndexRoute: AppIndexRoute,
  AppCommitteeInboxRoute: AppCommitteeInboxRoute,
  AppManagerCollectiveRoute: AppManagerCollectiveRoute,
  AppManagerResultRoute: AppManagerResultRoute,
  AppManagerResultsRoute: AppManagerResultsRouteWithChildren,
  AppReviewIdRoute: AppReviewIdRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
  SignupRoute: SignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
