/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/app'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as AppWizardRouteImport } from './routes/app.wizard'
import { Route as AppVnptRouteImport } from './routes/app.vnpt'
import { Route as AppUploadRouteImport } from './routes/app.upload'
import { Route as AppSmartuxRouteImport } from './routes/app.smartux'
import { Route as AppSettingsRouteImport } from './routes/app.settings'
import { Route as AppResultRouteImport } from './routes/app.result'
import { Route as AppResolutionRouteImport } from './routes/app.resolution'
import { Route as AppQueueRouteImport } from './routes/app.queue'
import { Route as AppProfileRouteImport } from './routes/app.profile'
import { Route as AppOverviewRouteImport } from './routes/app.overview'
import { Route as AppNotificationsRouteImport } from './routes/app.notifications'
import { Route as AppMyApplicationRouteImport } from './routes/app.my-application'
import { Route as AppFeedbackRouteImport } from './routes/app.feedback'
import { Route as AppExportRouteImport } from './routes/app.export'
import { Route as AppEvidenceSearchRouteImport } from './routes/app.evidence-search'
import { Route as AppEvidenceKnowledgeRouteImport } from './routes/app.evidence-knowledge'
import { Route as AppEvidenceRouteImport } from './routes/app.evidence'
import { Route as AppEventRegistryRouteImport } from './routes/app.event-registry'
import { Route as AppEventLibraryRouteImport } from './routes/app.event-library'
import { Route as AppEkycRouteImport } from './routes/app.ekyc'
import { Route as AppDraftsRouteImport } from './routes/app.drafts'
import { Route as AppDecisionImportsRouteImport } from './routes/app.decision-imports'
import { Route as AppDataUploaderRouteImport } from './routes/app.data-uploader'
import { Route as AppCollectiveRouteImport } from './routes/app.collective'
import { Route as AppChatbotRouteImport } from './routes/app.chatbot'
import { Route as AppCascadeRouteImport } from './routes/app.cascade'
import { Route as AppAwardRegistryRouteImport } from './routes/app.award-registry'
import { Route as AppAuditRouteImport } from './routes/app.audit'
import { Route as AppAssistantRouteImport } from './routes/app.assistant'
import { Route as AppAssignmentRouteImport } from './routes/app.assignment'
import { Route as AppApplicationRouteImport } from './routes/app.application'
import { Route as AppAnalyticsRouteImport } from './routes/app.analytics'
import { Route as AppAiPrecheckRouteImport } from './routes/app.ai-precheck'
import { Route as AppReviewIdRouteImport } from './routes/app.review.$id'
import { Route as AppResolutionIdRouteImport } from './routes/app.resolution.$id'
import { Route as AppManagerResultsRouteImport } from './routes/app.manager.results'
import { Route as AppManagerResultRouteImport } from './routes/app.manager.result'
import { Route as AppManagerCollectiveRouteImport } from './routes/app.manager.collective'
import { Route as AppDecisionImportsDecisionImportIdRouteImport } from './routes/app.decision-imports.$decisionImportId'
import { Route as AppCommitteeInboxRouteImport } from './routes/app.committee.inbox'
import { Route as AppCollectiveIdRouteImport } from './routes/app.collective.$id'
import { Route as AppAwardRegistryAwardDecisionIdRouteImport } from './routes/app.award-registry.$awardDecisionId'
import { Route as AppAdminWorkspacesRouteImport } from './routes/app.admin.workspaces'
import { Route as AppAdminWorkspaceRouteImport } from './routes/app.admin.workspace'
import { Route as AppAdminUsersRouteImport } from './routes/app.admin.users'
import { Route as AppAdminOfficersRouteImport } from './routes/app.admin.officers'
import { Route as AppManagerResultsApplicationIdRouteImport } from './routes/app.manager.results.$applicationId'
import { Route as AppAdminWorkspacesWorkspaceIdRouteImport } from './routes/app.admin.workspaces.$workspaceId'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppWizardRoute = AppWizardRouteImport.update({
  id: '/wizard',
  path: '/wizard',
  getParentRoute: () => AppRoute,
} as any)
const AppVnptRoute = AppVnptRouteImport.update({
  id: '/vnpt',
  path: '/vnpt',
  getParentRoute: () => AppRoute,
} as any)
const AppUploadRoute = AppUploadRouteImport.update({
  id: '/upload',
  path: '/upload',
  getParentRoute: () => AppRoute,
} as any)
const AppSmartuxRoute = AppSmartuxRouteImport.update({
  id: '/smartux',
  path: '/smartux',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppResultRoute = AppResultRouteImport.update({
  id: '/result',
  path: '/result',
  getParentRoute: () => AppRoute,
} as any)
const AppResolutionRoute = AppResolutionRouteImport.update({
  id: '/resolution',
  path: '/resolution',
  getParentRoute: () => AppRoute,
} as any)
const AppQueueRoute = AppQueueRouteImport.update({
  id: '/queue',
  path: '/queue',
  getParentRoute: () => AppRoute,
} as any)
const AppProfileRoute = AppProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AppRoute,
} as any)
const AppOverviewRoute = AppOverviewRouteImport.update({
  id: '/overview',
  path: '/overview',
  getParentRoute: () => AppRoute,
} as any)
const AppNotificationsRoute = AppNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => AppRoute,
} as any)
const AppMyApplicationRoute = AppMyApplicationRouteImport.update({
  id: '/my-application',
  path: '/my-application',
  getParentRoute: () => AppRoute,
} as any)
const AppFeedbackRoute = AppFeedbackRouteImport.update({
  id: '/feedback',
  path: '/feedback',
  getParentRoute: () => AppRoute,
} as any)
const AppExportRoute = AppExportRouteImport.update({
  id: '/export',
  path: '/export',
  getParentRoute: () => AppRoute,
} as any)
const AppEvidenceSearchRoute = AppEvidenceSearchRouteImport.update({
  id: '/evidence-search',
  path: '/evidence-search',
  getParentRoute: () => AppRoute,
} as any)
const AppEvidenceKnowledgeRoute = AppEvidenceKnowledgeRouteImport.update({
  id: '/evidence-knowledge',
  path: '/evidence-knowledge',
  getParentRoute: () => AppRoute,
} as any)
const AppEvidenceRoute = AppEvidenceRouteImport.update({
  id: '/evidence',
  path: '/evidence',
  getParentRoute: () => AppRoute,
} as any)
const AppEventRegistryRoute = AppEventRegistryRouteImport.update({
  id: '/event-registry',
  path: '/event-registry',
  getParentRoute: () => AppRoute,
} as any)
const AppEventLibraryRoute = AppEventLibraryRouteImport.update({
  id: '/event-library',
  path: '/event-library',
  getParentRoute: () => AppRoute,
} as any)
const AppEkycRoute = AppEkycRouteImport.update({
  id: '/ekyc',
  path: '/ekyc',
  getParentRoute: () => AppRoute,
} as any)
const AppDraftsRoute = AppDraftsRouteImport.update({
  id: '/drafts',
  path: '/drafts',
  getParentRoute: () => AppRoute,
} as any)
const AppDecisionImportsRoute = AppDecisionImportsRouteImport.update({
  id: '/decision-imports',
  path: '/decision-imports',
  getParentRoute: () => AppRoute,
} as any)
const AppDataUploaderRoute = AppDataUploaderRouteImport.update({
  id: '/data-uploader',
  path: '/data-uploader',
  getParentRoute: () => AppRoute,
} as any)
const AppCollectiveRoute = AppCollectiveRouteImport.update({
  id: '/collective',
  path: '/collective',
  getParentRoute: () => AppRoute,
} as any)
const AppChatbotRoute = AppChatbotRouteImport.update({
  id: '/chatbot',
  path: '/chatbot',
  getParentRoute: () => AppRoute,
} as any)
const AppCascadeRoute = AppCascadeRouteImport.update({
  id: '/cascade',
  path: '/cascade',
  getParentRoute: () => AppRoute,
} as any)
const AppAwardRegistryRoute = AppAwardRegistryRouteImport.update({
  id: '/award-registry',
  path: '/award-registry',
  getParentRoute: () => AppRoute,
} as any)
const AppAuditRoute = AppAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => AppRoute,
} as any)
const AppAssistantRoute = AppAssistantRouteImport.update({
  id: '/assistant',
  path: '/assistant',
  getParentRoute: () => AppRoute,
} as any)
const AppAssignmentRoute = AppAssignmentRouteImport.update({
  id: '/assignment',
  path: '/assignment',
  getParentRoute: () => AppRoute,
} as any)
const AppApplicationRoute = AppApplicationRouteImport.update({
  id: '/application',
  path: '/application',
  getParentRoute: () => AppRoute,
} as any)
const AppAnalyticsRoute = AppAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AppRoute,
} as any)
const AppAiPrecheckRoute = AppAiPrecheckRouteImport.update({
  id: '/ai-precheck',
  path: '/ai-precheck',
  getParentRoute: () => AppRoute,
} as any)
const AppReviewIdRoute = AppReviewIdRouteImport.update({
  id: '/review/$id',
  path: '/review/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppResolutionIdRoute = AppResolutionIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AppResolutionRoute,
} as any)
const AppManagerResultsRoute = AppManagerResultsRouteImport.update({
  id: '/manager/results',
  path: '/manager/results',
  getParentRoute: () => AppRoute,
} as any)
const AppManagerResultRoute = AppManagerResultRouteImport.update({
  id: '/manager/result',
  path: '/manager/result',
  getParentRoute: () => AppRoute,
} as any)
const AppManagerCollectiveRoute = AppManagerCollectiveRouteImport.update({
  id: '/manager/collective',
  path: '/manager/collective',
  getParentRoute: () => AppRoute,
} as any)
const AppDecisionImportsDecisionImportIdRoute =
  AppDecisionImportsDecisionImportIdRouteImport.update({
    id: '/$decisionImportId',
    path: '/$decisionImportId',
    getParentRoute: () => AppDecisionImportsRoute,
  } as any)
const AppCommitteeInboxRoute = AppCommitteeInboxRouteImport.update({
  id: '/committee/inbox',
  path: '/committee/inbox',
  getParentRoute: () => AppRoute,
} as any)
const AppCollectiveIdRoute = AppCollectiveIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AppCollectiveRoute,
} as any)
const AppAwardRegistryAwardDecisionIdRoute =
  AppAwardRegistryAwardDecisionIdRouteImport.update({
    id: '/$awardDecisionId',
    path: '/$awardDecisionId',
    getParentRoute: () => AppAwardRegistryRoute,
  } as any)
const AppAdminWorkspacesRoute = AppAdminWorkspacesRouteImport.update({
  id: '/admin/workspaces',
  path: '/admin/workspaces',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminWorkspaceRoute = AppAdminWorkspaceRouteImport.update({
  id: '/admin/workspace',
  path: '/admin/workspace',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminUsersRoute = AppAdminUsersRouteImport.update({
  id: '/admin/users',
  path: '/admin/users',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminOfficersRoute = AppAdminOfficersRouteImport.update({
  id: '/admin/officers',
  path: '/admin/officers',
  getParentRoute: () => AppRoute,
} as any)
const AppManagerResultsApplicationIdRoute =
  AppManagerResultsApplicationIdRouteImport.update({
    id: '/$applicationId',
    path: '/$applicationId',
    getParentRoute: () => AppManagerResultsRoute,
  } as any)
const AppAdminWorkspacesWorkspaceIdRoute =
  AppAdminWorkspacesWorkspaceIdRouteImport.update({
    id: '/$workspaceId',
    path: '/$workspaceId',
    getParentRoute: () => AppAdminWorkspacesRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/app/ai-precheck': typeof AppAiPrecheckRoute
  '/app/analytics': typeof AppAnalyticsRoute
  '/app/application': typeof AppApplicationRoute
  '/app/assignment': typeof AppAssignmentRoute
  '/app/assistant': typeof AppAssistantRoute
  '/app/audit': typeof AppAuditRoute
  '/app/award-registry': typeof AppAwardRegistryRouteWithChildren
  '/app/cascade': typeof AppCascadeRoute
  '/app/chatbot': typeof AppChatbotRoute
  '/app/collective': typeof AppCollectiveRouteWithChildren
  '/app/data-uploader': typeof AppDataUploaderRoute
  '/app/decision-imports': typeof AppDecisionImportsRouteWithChildren
  '/app/drafts': typeof AppDraftsRoute
  '/app/ekyc': typeof AppEkycRoute
  '/app/event-library': typeof AppEventLibraryRoute
  '/app/event-registry': typeof AppEventRegistryRoute
  '/app/evidence': typeof AppEvidenceRoute
  '/app/evidence-knowledge': typeof AppEvidenceKnowledgeRoute
  '/app/evidence-search': typeof AppEvidenceSearchRoute
  '/app/export': typeof AppExportRoute
  '/app/feedback': typeof AppFeedbackRoute
  '/app/my-application': typeof AppMyApplicationRoute
  '/app/notifications': typeof AppNotificationsRoute
  '/app/overview': typeof AppOverviewRoute
  '/app/profile': typeof AppProfileRoute
  '/app/queue': typeof AppQueueRoute
  '/app/resolution': typeof AppResolutionRouteWithChildren
  '/app/result': typeof AppResultRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/smartux': typeof AppSmartuxRoute
  '/app/upload': typeof AppUploadRoute
  '/app/vnpt': typeof AppVnptRoute
  '/app/wizard': typeof AppWizardRoute
  '/app/': typeof AppIndexRoute
  '/app/admin/officers': typeof AppAdminOfficersRoute
  '/app/admin/users': typeof AppAdminUsersRoute
  '/app/admin/workspace': typeof AppAdminWorkspaceRoute
  '/app/admin/workspaces': typeof AppAdminWorkspacesRouteWithChildren
  '/app/award-registry/$awardDecisionId': typeof AppAwardRegistryAwardDecisionIdRoute
  '/app/collective/$id': typeof AppCollectiveIdRoute
  '/app/committee/inbox': typeof AppCommitteeInboxRoute
  '/app/decision-imports/$decisionImportId': typeof AppDecisionImportsDecisionImportIdRoute
  '/app/manager/collective': typeof AppManagerCollectiveRoute
  '/app/manager/result': typeof AppManagerResultRoute
  '/app/manager/results': typeof AppManagerResultsRouteWithChildren
  '/app/resolution/$id': typeof AppResolutionIdRoute
  '/app/review/$id': typeof AppReviewIdRoute
  '/app/admin/workspaces/$workspaceId': typeof AppAdminWorkspacesWorkspaceIdRoute
  '/app/manager/results/$applicationId': typeof AppManagerResultsApplicationIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/app/ai-precheck': typeof AppAiPrecheckRoute
  '/app/analytics': typeof AppAnalyticsRoute
  '/app/application': typeof AppApplicationRoute
  '/app/assignment': typeof AppAssignmentRoute
  '/app/assistant': typeof AppAssistantRoute
  '/app/audit': typeof AppAuditRoute
  '/app/award-registry': typeof AppAwardRegistryRouteWithChildren
  '/app/cascade': typeof AppCascadeRoute
  '/app/chatbot': typeof AppChatbotRoute
  '/app/collective': typeof AppCollectiveRouteWithChildren
  '/app/data-uploader': typeof AppDataUploaderRoute
  '/app/decision-imports': typeof AppDecisionImportsRouteWithChildren
  '/app/drafts': typeof AppDraftsRoute
  '/app/ekyc': typeof AppEkycRoute
  '/app/event-library': typeof AppEventLibraryRoute
  '/app/event-registry': typeof AppEventRegistryRoute
  '/app/evidence': typeof AppEvidenceRoute
  '/app/evidence-knowledge': typeof AppEvidenceKnowledgeRoute
  '/app/evidence-search': typeof AppEvidenceSearchRoute
  '/app/export': typeof AppExportRoute
  '/app/feedback': typeof AppFeedbackRoute
  '/app/my-application': typeof AppMyApplicationRoute
  '/app/notifications': typeof AppNotificationsRoute
  '/app/overview': typeof AppOverviewRoute
  '/app/profile': typeof AppProfileRoute
  '/app/queue': typeof AppQueueRoute
  '/app/resolution': typeof AppResolutionRouteWithChildren
  '/app/result': typeof AppResultRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/smartux': typeof AppSmartuxRoute
  '/app/upload': typeof AppUploadRoute
  '/app/vnpt': typeof AppVnptRoute
  '/app/wizard': typeof AppWizardRoute
  '/app': typeof AppIndexRoute
  '/app/admin/officers': typeof AppAdminOfficersRoute
  '/app/admin/users': typeof AppAdminUsersRoute
  '/app/admin/workspace': typeof AppAdminWorkspaceRoute
  '/app/admin/workspaces': typeof AppAdminWorkspacesRouteWithChildren
  '/app/award-registry/$awardDecisionId': typeof AppAwardRegistryAwardDecisionIdRoute
  '/app/collective/$id': typeof AppCollectiveIdRoute
  '/app/committee/inbox': typeof AppCommitteeInboxRoute
  '/app/decision-imports/$decisionImportId': typeof AppDecisionImportsDecisionImportIdRoute
  '/app/manager/collective': typeof AppManagerCollectiveRoute
  '/app/manager/result': typeof AppManagerResultRoute
  '/app/manager/results': typeof AppManagerResultsRouteWithChildren
  '/app/resolution/$id': typeof AppResolutionIdRoute
  '/app/review/$id': typeof AppReviewIdRoute
  '/app/admin/workspaces/$workspaceId': typeof AppAdminWorkspacesWorkspaceIdRoute
  '/app/manager/results/$applicationId': typeof AppManagerResultsApplicationIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/app/ai-precheck': typeof AppAiPrecheckRoute
  '/app/analytics': typeof AppAnalyticsRoute
  '/app/application': typeof AppApplicationRoute
  '/app/assignment': typeof AppAssignmentRoute
  '/app/assistant': typeof AppAssistantRoute
  '/app/audit': typeof AppAuditRoute
  '/app/award-registry': typeof AppAwardRegistryRouteWithChildren
  '/app/cascade': typeof AppCascadeRoute
  '/app/chatbot': typeof AppChatbotRoute
  '/app/collective': typeof AppCollectiveRouteWithChildren
  '/app/data-uploader': typeof AppDataUploaderRoute
  '/app/decision-imports': typeof AppDecisionImportsRouteWithChildren
  '/app/drafts': typeof AppDraftsRoute
  '/app/ekyc': typeof AppEkycRoute
  '/app/event-library': typeof AppEventLibraryRoute
  '/app/event-registry': typeof AppEventRegistryRoute
  '/app/evidence': typeof AppEvidenceRoute
  '/app/evidence-knowledge': typeof AppEvidenceKnowledgeRoute
  '/app/evidence-search': typeof AppEvidenceSearchRoute
  '/app/export': typeof AppExportRoute
  '/app/feedback': typeof AppFeedbackRoute
  '/app/my-application': typeof AppMyApplicationRoute
  '/app/notifications': typeof AppNotificationsRoute
  '/app/overview': typeof AppOverviewRoute
  '/app/profile': typeof AppProfileRoute
  '/app/queue': typeof AppQueueRoute
  '/app/resolution': typeof AppResolutionRouteWithChildren
  '/app/result': typeof AppResultRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/smartux': typeof AppSmartuxRoute
  '/app/upload': typeof AppUploadRoute
  '/app/vnpt': typeof AppVnptRoute
  '/app/wizard': typeof AppWizardRoute
  '/app/': typeof AppIndexRoute
  '/app/admin/officers': typeof AppAdminOfficersRoute
  '/app/admin/users': typeof AppAdminUsersRoute
  '/app/admin/workspace': typeof AppAdminWorkspaceRoute
  '/app/admin/workspaces': typeof AppAdminWorkspacesRouteWithChildren
  '/app/award-registry/$awardDecisionId': typeof AppAwardRegistryAwardDecisionIdRoute
  '/app/collective/$id': typeof AppCollectiveIdRoute
  '/app/committee/inbox': typeof AppCommitteeInboxRoute
  '/app/decision-imports/$decisionImportId': typeof AppDecisionImportsDecisionImportIdRoute
  '/app/manager/collective': typeof AppManagerCollectiveRoute
  '/app/manager/result': typeof AppManagerResultRoute
  '/app/manager/results': typeof AppManagerResultsRouteWithChildren
  '/app/resolution/$id': typeof AppResolutionIdRoute
  '/app/review/$id': typeof AppReviewIdRoute
  '/app/admin/workspaces/$workspaceId': typeof AppAdminWorkspacesWorkspaceIdRoute
  '/app/manager/results/$applicationId': typeof AppManagerResultsApplicationIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/app'
    | '/login'
    | '/signup'
    | '/app/ai-precheck'
    | '/app/analytics'
    | '/app/application'
    | '/app/assignment'
    | '/app/assistant'
    | '/app/audit'
    | '/app/award-registry'
    | '/app/cascade'
    | '/app/chatbot'
    | '/app/collective'
    | '/app/data-uploader'
    | '/app/decision-imports'
    | '/app/drafts'
    | '/app/ekyc'
    | '/app/event-library'
    | '/app/event-registry'
    | '/app/evidence'
    | '/app/evidence-knowledge'
    | '/app/evidence-search'
    | '/app/export'
    | '/app/feedback'
    | '/app/my-application'
    | '/app/notifications'
    | '/app/overview'
    | '/app/profile'
    | '/app/queue'
    | '/app/resolution'
    | '/app/result'
    | '/app/settings'
    | '/app/smartux'
    | '/app/upload'
    | '/app/vnpt'
    | '/app/wizard'
    | '/app/'
    | '/app/admin/officers'
    | '/app/admin/users'
    | '/app/admin/workspace'
    | '/app/admin/workspaces'
    | '/app/award-registry/$awardDecisionId'
    | '/app/collective/$id'
    | '/app/committee/inbox'
    | '/app/decision-imports/$decisionImportId'
    | '/app/manager/collective'
    | '/app/manager/result'
    | '/app/manager/results'
    | '/app/resolution/$id'
    | '/app/review/$id'
    | '/app/admin/workspaces/$workspaceId'
    | '/app/manager/results/$applicationId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/login'
    | '/signup'
    | '/app/ai-precheck'
    | '/app/analytics'
    | '/app/application'
    | '/app/assignment'
    | '/app/assistant'
    | '/app/audit'
    | '/app/award-registry'
    | '/app/cascade'
    | '/app/chatbot'
    | '/app/collective'
    | '/app/data-uploader'
    | '/app/decision-imports'
    | '/app/drafts'
    | '/app/ekyc'
    | '/app/event-library'
    | '/app/event-registry'
    | '/app/evidence'
    | '/app/evidence-knowledge'
    | '/app/evidence-search'
    | '/app/export'
    | '/app/feedback'
    | '/app/my-application'
    | '/app/notifications'
    | '/app/overview'
    | '/app/profile'
    | '/app/queue'
    | '/app/resolution'
    | '/app/result'
    | '/app/settings'
    | '/app/smartux'
    | '/app/upload'
    | '/app/vnpt'
    | '/app/wizard'
    | '/app'
    | '/app/admin/officers'
    | '/app/admin/users'
    | '/app/admin/workspace'
    | '/app/admin/workspaces'
    | '/app/award-registry/$awardDecisionId'
    | '/app/collective/$id'
    | '/app/committee/inbox'
    | '/app/decision-imports/$decisionImportId'
    | '/app/manager/collective'
    | '/app/manager/result'
    | '/app/manager/results'
    | '/app/resolution/$id'
    | '/app/review/$id'
    | '/app/admin/workspaces/$workspaceId'
    | '/app/manager/results/$applicationId'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/app'
    | '/login'
    | '/signup'
    | '/app/ai-precheck'
    | '/app/analytics'
    | '/app/application'
    | '/app/assignment'
    | '/app/assistant'
    | '/app/audit'
    | '/app/award-registry'
    | '/app/cascade'
    | '/app/chatbot'
    | '/app/collective'
    | '/app/data-uploader'
    | '/app/decision-imports'
    | '/app/drafts'
    | '/app/ekyc'
    | '/app/event-library'
    | '/app/event-registry'
    | '/app/evidence'
    | '/app/evidence-knowledge'
    | '/app/evidence-search'
    | '/app/export'
    | '/app/feedback'
    | '/app/my-application'
    | '/app/notifications'
    | '/app/overview'
    | '/app/profile'
    | '/app/queue'
    | '/app/resolution'
    | '/app/result'
    | '/app/settings'
    | '/app/smartux'
    | '/app/upload'
    | '/app/vnpt'
    | '/app/wizard'
    | '/app/'
    | '/app/admin/officers'
    | '/app/admin/users'
    | '/app/admin/workspace'
    | '/app/admin/workspaces'
    | '/app/award-registry/$awardDecisionId'
    | '/app/collective/$id'
    | '/app/committee/inbox'
    | '/app/decision-imports/$decisionImportId'
    | '/app/manager/collective'
    | '/app/manager/result'
    | '/app/manager/results'
    | '/app/resolution/$id'
    | '/app/review/$id'
    | '/app/admin/workspaces/$workspaceId'
    | '/app/manager/results/$applicationId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
  SignupRoute: typeof SignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/wizard': {
      id: '/app/wizard'
      path: '/wizard'
      fullPath: '/app/wizard'
      preLoaderRoute: typeof AppWizardRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/vnpt': {
      id: '/app/vnpt'
      path: '/vnpt'
      fullPath: '/app/vnpt'
      preLoaderRoute: typeof AppVnptRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/upload': {
      id: '/app/upload'
      path: '/upload'
      fullPath: '/app/upload'
      preLoaderRoute: typeof AppUploadRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/smartux': {
      id: '/app/smartux'
      path: '/smartux'
      fullPath: '/app/smartux'
      preLoaderRoute: typeof AppSmartuxRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/settings': {
      id: '/app/settings'
      path: '/settings'
      fullPath: '/app/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/result': {
      id: '/app/result'
      path: '/result'
      fullPath: '/app/result'
      preLoaderRoute: typeof AppResultRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/resolution': {
      id: '/app/resolution'
      path: '/resolution'
      fullPath: '/app/resolution'
      preLoaderRoute: typeof AppResolutionRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/queue': {
      id: '/app/queue'
      path: '/queue'
      fullPath: '/app/queue'
      preLoaderRoute: typeof AppQueueRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/profile': {
      id: '/app/profile'
      path: '/profile'
      fullPath: '/app/profile'
      preLoaderRoute: typeof AppProfileRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/overview': {
      id: '/app/overview'
      path: '/overview'
      fullPath: '/app/overview'
      preLoaderRoute: typeof AppOverviewRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/notifications': {
      id: '/app/notifications'
      path: '/notifications'
      fullPath: '/app/notifications'
      preLoaderRoute: typeof AppNotificationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/my-application': {
      id: '/app/my-application'
      path: '/my-application'
      fullPath: '/app/my-application'
      preLoaderRoute: typeof AppMyApplicationRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/feedback': {
      id: '/app/feedback'
      path: '/feedback'
      fullPath: '/app/feedback'
      preLoaderRoute: typeof AppFeedbackRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/export': {
      id: '/app/export'
      path: '/export'
      fullPath: '/app/export'
      preLoaderRoute: typeof AppExportRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/evidence-search': {
      id: '/app/evidence-search'
      path: '/evidence-search'
      fullPath: '/app/evidence-search'
      preLoaderRoute: typeof AppEvidenceSearchRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/evidence-knowledge': {
      id: '/app/evidence-knowledge'
      path: '/evidence-knowledge'
      fullPath: '/app/evidence-knowledge'
      preLoaderRoute: typeof AppEvidenceKnowledgeRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/evidence': {
      id: '/app/evidence'
      path: '/evidence'
      fullPath: '/app/evidence'
      preLoaderRoute: typeof AppEvidenceRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/event-registry': {
      id: '/app/event-registry'
      path: '/event-registry'
      fullPath: '/app/event-registry'
      preLoaderRoute: typeof AppEventRegistryRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/event-library': {
      id: '/app/event-library'
      path: '/event-library'
      fullPath: '/app/event-library'
      preLoaderRoute: typeof AppEventLibraryRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/ekyc': {
      id: '/app/ekyc'
      path: '/ekyc'
      fullPath: '/app/ekyc'
      preLoaderRoute: typeof AppEkycRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/drafts': {
      id: '/app/drafts'
      path: '/drafts'
      fullPath: '/app/drafts'
      preLoaderRoute: typeof AppDraftsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/decision-imports': {
      id: '/app/decision-imports'
      path: '/decision-imports'
      fullPath: '/app/decision-imports'
      preLoaderRoute: typeof AppDecisionImportsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/data-uploader': {
      id: '/app/data-uploader'
      path: '/data-uploader'
      fullPath: '/app/data-uploader'
      preLoaderRoute: typeof AppDataUploaderRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/collective': {
      id: '/app/collective'
      path: '/collective'
      fullPath: '/app/collective'
      preLoaderRoute: typeof AppCollectiveRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/chatbot': {
      id: '/app/chatbot'
      path: '/chatbot'
      fullPath: '/app/chatbot'
      preLoaderRoute: typeof AppChatbotRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/cascade': {
      id: '/app/cascade'
      path: '/cascade'
      fullPath: '/app/cascade'
      preLoaderRoute: typeof AppCascadeRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/award-registry': {
      id: '/app/award-registry'
      path: '/award-registry'
      fullPath: '/app/award-registry'
      preLoaderRoute: typeof AppAwardRegistryRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/audit': {
      id: '/app/audit'
      path: '/audit'
      fullPath: '/app/audit'
      preLoaderRoute: typeof AppAuditRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/assistant': {
      id: '/app/assistant'
      path: '/assistant'
      fullPath: '/app/assistant'
      preLoaderRoute: typeof AppAssistantRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/assignment': {
      id: '/app/assignment'
      path: '/assignment'
      fullPath: '/app/assignment'
      preLoaderRoute: typeof AppAssignmentRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/application': {
      id: '/app/application'
      path: '/application'
      fullPath: '/app/application'
      preLoaderRoute: typeof AppApplicationRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/analytics': {
      id: '/app/analytics'
      path: '/analytics'
      fullPath: '/app/analytics'
      preLoaderRoute: typeof AppAnalyticsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/ai-precheck': {
      id: '/app/ai-precheck'
      path: '/ai-precheck'
      fullPath: '/app/ai-precheck'
      preLoaderRoute: typeof AppAiPrecheckRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/review/$id': {
      id: '/app/review/$id'
      path: '/review/$id'
      fullPath: '/app/review/$id'
      preLoaderRoute: typeof AppReviewIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/resolution/$id': {
      id: '/app/resolution/$id'
      path: '/$id'
      fullPath: '/app/resolution/$id'
      preLoaderRoute: typeof AppResolutionIdRouteImport
      parentRoute: typeof AppResolutionRoute
    }
    '/app/manager/results': {
      id: '/app/manager/results'
      path: '/manager/results'
      fullPath: '/app/manager/results'
      preLoaderRoute: typeof AppManagerResultsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/manager/result': {
      id: '/app/manager/result'
      path: '/manager/result'
      fullPath: '/app/manager/result'
      preLoaderRoute: typeof AppManagerResultRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/manager/collective': {
      id: '/app/manager/collective'
      path: '/manager/collective'
      fullPath: '/app/manager/collective'
      preLoaderRoute: typeof AppManagerCollectiveRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/decision-imports/$decisionImportId': {
      id: '/app/decision-imports/$decisionImportId'
      path: '/$decisionImportId'
      fullPath: '/app/decision-imports/$decisionImportId'
      preLoaderRoute: typeof AppDecisionImportsDecisionImportIdRouteImport
      parentRoute: typeof AppDecisionImportsRoute
    }
    '/app/committee/inbox': {
      id: '/app/committee/inbox'
      path: '/committee/inbox'
      fullPath: '/app/committee/inbox'
      preLoaderRoute: typeof AppCommitteeInboxRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/collective/$id': {
      id: '/app/collective/$id'
      path: '/$id'
      fullPath: '/app/collective/$id'
      preLoaderRoute: typeof AppCollectiveIdRouteImport
      parentRoute: typeof AppCollectiveRoute
    }
    '/app/award-registry/$awardDecisionId': {
      id: '/app/award-registry/$awardDecisionId'
      path: '/$awardDecisionId'
      fullPath: '/app/award-registry/$awardDecisionId'
      preLoaderRoute: typeof AppAwardRegistryAwardDecisionIdRouteImport
      parentRoute: typeof AppAwardRegistryRoute
    }
    '/app/admin/workspaces': {
      id: '/app/admin/workspaces'
      path: '/admin/workspaces'
      fullPath: '/app/admin/workspaces'
      preLoaderRoute: typeof AppAdminWorkspacesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/admin/workspace': {
      id: '/app/admin/workspace'
      path: '/admin/workspace'
      fullPath: '/app/admin/workspace'
      preLoaderRoute: typeof AppAdminWorkspaceRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/admin/users': {
      id: '/app/admin/users'
      path: '/admin/users'
      fullPath: '/app/admin/users'
      preLoaderRoute: typeof AppAdminUsersRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/admin/officers': {
      id: '/app/admin/officers'
      path: '/admin/officers'
      fullPath: '/app/admin/officers'
      preLoaderRoute: typeof AppAdminOfficersRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/manager/results/$applicationId': {
      id: '/app/manager/results/$applicationId'
      path: '/$applicationId'
      fullPath: '/app/manager/results/$applicationId'
      preLoaderRoute: typeof AppManagerResultsApplicationIdRouteImport
      parentRoute: typeof AppManagerResultsRoute
    }
    '/app/admin/workspaces/$workspaceId': {
      id: '/app/admin/workspaces/$workspaceId'
      path: '/$workspaceId'
      fullPath: '/app/admin/workspaces/$workspaceId'
      preLoaderRoute: typeof AppAdminWorkspacesWorkspaceIdRouteImport
      parentRoute: typeof AppAdminWorkspacesRoute
    }
  }
}

interface AppAwardRegistryRouteChildren {
  AppAwardRegistryAwardDecisionIdRoute: typeof AppAwardRegistryAwardDecisionIdRoute
}

const AppAwardRegistryRouteChildren: AppAwardRegistryRouteChildren = {
  AppAwardRegistryAwardDecisionIdRoute: AppAwardRegistryAwardDecisionIdRoute,
}

const AppAwardRegistryRouteWithChildren =
  AppAwardRegistryRoute._addFileChildren(AppAwardRegistryRouteChildren)

interface AppCollectiveRouteChildren {
  AppCollectiveIdRoute: typeof AppCollectiveIdRoute
}

const AppCollectiveRouteChildren: AppCollectiveRouteChildren = {
  AppCollectiveIdRoute: AppCollectiveIdRoute,
}

const AppCollectiveRouteWithChildren = AppCollectiveRoute._addFileChildren(
  AppCollectiveRouteChildren,
)

interface AppDecisionImportsRouteChildren {
  AppDecisionImportsDecisionImportIdRoute: typeof AppDecisionImportsDecisionImportIdRoute
}

const AppDecisionImportsRouteChildren: AppDecisionImportsRouteChildren = {
  AppDecisionImportsDecisionImportIdRoute:
    AppDecisionImportsDecisionImportIdRoute,
}

const AppDecisionImportsRouteWithChildren =
  AppDecisionImportsRoute._addFileChildren(AppDecisionImportsRouteChildren)

interface AppResolutionRouteChildren {
  AppResolutionIdRoute: typeof AppResolutionIdRoute
}

const AppResolutionRouteChildren: AppResolutionRouteChildren = {
  AppResolutionIdRoute: AppResolutionIdRoute,
}

const AppResolutionRouteWithChildren = AppResolutionRoute._addFileChildren(
  AppResolutionRouteChildren,
)

interface AppAdminWorkspacesRouteChildren {
  AppAdminWorkspacesWorkspaceIdRoute: typeof AppAdminWorkspacesWorkspaceIdRoute
}

const AppAdminWorkspacesRouteChildren: AppAdminWorkspacesRouteChildren = {
  AppAdminWorkspacesWorkspaceIdRoute: AppAdminWorkspacesWorkspaceIdRoute,
}

const AppAdminWorkspacesRouteWithChildren =
  AppAdminWorkspacesRoute._addFileChildren(AppAdminWorkspacesRouteChildren)

interface AppManagerResultsRouteChildren {
  AppManagerResultsApplicationIdRoute: typeof AppManagerResultsApplicationIdRoute
}

const AppManagerResultsRouteChildren: AppManagerResultsRouteChildren = {
  AppManagerResultsApplicationIdRoute: AppManagerResultsApplicationIdRoute,
}

const AppManagerResultsRouteWithChildren =
  AppManagerResultsRoute._addFileChildren(AppManagerResultsRouteChildren)

interface AppRouteChildren {
  AppAiPrecheckRoute: typeof AppAiPrecheckRoute
  AppAnalyticsRoute: typeof AppAnalyticsRoute
  AppApplicationRoute: typeof AppApplicationRoute
  AppAssignmentRoute: typeof AppAssignmentRoute
  AppAssistantRoute: typeof AppAssistantRoute
  AppAuditRoute: typeof AppAuditRoute
  AppAwardRegistryRoute: typeof AppAwardRegistryRouteWithChildren
  AppCascadeRoute: typeof AppCascadeRoute
  AppChatbotRoute: typeof AppChatbotRoute
  AppCollectiveRoute: typeof AppCollectiveRouteWithChildren
  AppDataUploaderRoute: typeof AppDataUploaderRoute
  AppDecisionImportsRoute: typeof AppDecisionImportsRouteWithChildren
  AppDraftsRoute: typeof AppDraftsRoute
  AppEkycRoute: typeof AppEkycRoute
  AppEventLibraryRoute: typeof AppEventLibraryRoute
  AppEventRegistryRoute: typeof AppEventRegistryRoute
  AppEvidenceRoute: typeof AppEvidenceRoute
  AppEvidenceKnowledgeRoute: typeof AppEvidenceKnowledgeRoute
  AppEvidenceSearchRoute: typeof AppEvidenceSearchRoute
  AppExportRoute: typeof AppExportRoute
  AppFeedbackRoute: typeof AppFeedbackRoute
  AppMyApplicationRoute: typeof AppMyApplicationRoute
  AppNotificationsRoute: typeof AppNotificationsRoute
  AppOverviewRoute: typeof AppOverviewRoute
  AppProfileRoute: typeof AppProfileRoute
  AppQueueRoute: typeof AppQueueRoute
  AppResolutionRoute: typeof AppResolutionRouteWithChildren
  AppResultRoute: typeof AppResultRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppSmartuxRoute: typeof AppSmartuxRoute
  AppUploadRoute: typeof AppUploadRoute
  AppVnptRoute: typeof AppVnptRoute
  AppWizardRoute: typeof AppWizardRoute
  AppIndexRoute: typeof AppIndexRoute
  AppAdminOfficersRoute: typeof AppAdminOfficersRoute
  AppAdminUsersRoute: typeof AppAdminUsersRoute
  AppAdminWorkspaceRoute: typeof AppAdminWorkspaceRoute
  AppAdminWorkspacesRoute: typeof AppAdminWorkspacesRouteWithChildren
  AppCommitteeInboxRoute: typeof AppCommitteeInboxRoute
  AppManagerCollectiveRoute: typeof AppManagerCollectiveRoute
  AppManagerResultRoute: typeof AppManagerResultRoute
  AppManagerResultsRoute: typeof AppManagerResultsRouteWithChildren
  AppReviewIdRoute: typeof AppReviewIdRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAiPrecheckRoute: AppAiPrecheckRoute,
  AppAnalyticsRoute: AppAnalyticsRoute,
  AppApplicationRoute: AppApplicationRoute,
  AppAssignmentRoute: AppAssignmentRoute,
  AppAssistantRoute: AppAssistantRoute,
  AppAuditRoute: AppAuditRoute,
  AppAwardRegistryRoute: AppAwardRegistryRouteWithChildren,
  AppCascadeRoute: AppCascadeRoute,
  AppChatbotRoute: AppChatbotRoute,
  AppCollectiveRoute: AppCollectiveRouteWithChildren,
  AppDataUploaderRoute: AppDataUploaderRoute,
  AppDecisionImportsRoute: AppDecisionImportsRouteWithChildren,
  AppDraftsRoute: AppDraftsRoute,
  AppEkycRoute: AppEkycRoute,
  AppEventLibraryRoute: AppEventLibraryRoute,
  AppEventRegistryRoute: AppEventRegistryRoute,
  AppEvidenceRoute: AppEvidenceRoute,
  AppEvidenceKnowledgeRoute: AppEvidenceKnowledgeRoute,
  AppEvidenceSearchRoute: AppEvidenceSearchRoute,
  AppExportRoute: AppExportRoute,
  AppFeedbackRoute: AppFeedbackRoute,
  AppMyApplicationRoute: AppMyApplicationRoute,
  AppNotificationsRoute: AppNotificationsRoute,
  AppOverviewRoute: AppOverviewRoute,
  AppProfileRoute: AppProfileRoute,
  AppQueueRoute: AppQueueRoute,
  AppResolutionRoute: AppResolutionRouteWithChildren,
  AppResultRoute: AppResultRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppSmartuxRoute: AppSmartuxRoute,
  AppUploadRoute: AppUploadRoute,
  AppVnptRoute: AppVnptRoute,
  AppWizardRoute: AppWizardRoute,
  AppIndexRoute: AppIndexRoute,
  AppAdminOfficersRoute: AppAdminOfficersRoute,
  AppAdminUsersRoute: AppAdminUsersRoute,
  AppAdminWorkspaceRoute: AppAdminWorkspaceRoute,
  AppAdminWorkspacesRoute: AppAdminWorkspacesRouteWithChildren,
  AppCommitteeInboxRoute: AppCommitteeInboxRoute,
  AppManagerCollectiveRoute: AppManagerCollectiveRoute,
  AppManagerResultRoute: AppManagerResultRoute,
  AppManagerResultsRoute: AppManagerResultsRouteWithChildren,
  AppReviewIdRoute: AppReviewIdRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
  SignupRoute: SignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
